### PR TITLE
Test/refactor

### PR DESCRIPTION
**Pull request by jakinyang**
This offers a complete refactor of the project and establishes a base structure for the app.

### CODE REVIEW

**Comment by jakinyang** [comment]
#17 This addresses the layout of the application and starts the process of finalizing the screens.

**Review by Bohjaangles — APPROVED** [review]
Its looking good, useful reformatting for readabiliity, and folder/file navigation. Good work!

**Comment by jakinyang** [comment]
Nice, I'm glad. Still some refactoring to do, but it's a good place to start.

**Comment by jakinyang** [comment]
Just referencing issue #17 was resolved in this update.

**Review by Benjamin0203 — APPROVED** [review]
Looks good to me, thank you guys for the hard work!

**Pull request merged**
