### PR TITLE
Feature/report history

### PR DESCRIPTION
**Pull request by Bohjaangles**
added a working and rendering carousel to the history screen in profile tab, reflecting dummy data for user reports via carousel

- still needs implementation to click on a report from the carousel to render the individual card in its own screen. To be accomplished in a new feature branch after initial carousel merge

### CODE REVIEW

**Review by Benjamin0203 — COMMENTED** [review]
checking: yarn removed

**Review by jakinyang — COMMENTED** [review]
Everything looks great Russel!

**Review by jakinyang — APPROVED** [review]
I'm going to approve this merge

**Comment by jakinyang** [comment]
Hey this addresses this issue as well #16

**Comment by Bohjaangles** [comment]
Hey guys, this is my pull reqruest, adressing this issue: #20

**Comment by jakinyang** [comment]
Good job addressing this issue @Bohjaangles #37

**Comment by Benjamin0203** [comment]
Good job addressing this issue #32

**Pull request merged**
